export const labelConfig = {
  alferix: {
    employees: "Employees",
    calendar: "Calendar",
    leave: "Leave",
    id: "id",
    leaves: "Leaves",
    all: "All",
    allValue: "all",
    complete: "complete",
    pending: "pending",
    current: "current",
    invalid: "invalid",
    sickLeaveValue: "sickLeave",
    sickLeave: "Sick Leave",
    casualLeaveValue: "casualLeave",
    casualLeave: "Casual Leave",
    compOffValue: "compOff",
    compOff: "Comp Off",
    holidayValue: "holidays",
    holidays: "Holidays",
    optionalHoliday: "Optional Holiday",
    optionalHolidayValue: "optionalHoliday",
    rejectedLeaves: "Rejected Leaves",
    rejectedLeavesValue: "rejectedLeaves",
    availedLeavesValue: "availedLeaves",
    availedLeaves: "Availed Leaves",
    employee: "Employee",
    empId: "empId",
    navigateToLeave: "Go to Leave Calendar",
    home: "Home",
    edit: "Edit",
    delete: "Delete",
    close: "Close",
    submit: "Submit",
    save: "Save",
    next: "Next",
    back: "Back",
    personalInformationText: "Personal Information",
    personalInfoDesc: "Basic information for an account opening",
    personalInformation: {
      firstName: "First Name",
      lastName: "Last Name",
      gender: "Gender",
      maritalStatus: "Marital Status",
      nationality: "Nationality",
      phoneNumber: "Phone Number",
      dob: "Date of Birth",
      dialCode: "Dial Code",
      age: "Age",
      city: "City",
      email: "Email",
    },
    personalInformationLowerCase: {
      firstName: "firstName",
      lastName: "lastName",
      gender: "gender",
      maritalStatus: "maritalStatus",
      nationality: "nationality",
      phoneNumber: "phoneNumber",
      dob: "dob",
      dialCode: "dialCode",
      email: "email",
    },
    identityInfo: {
      documentTypeLowerCase: "documentType",
      documentTypeHeader: "Select your document type",
      documentTypes: [
        { value: "passport", label: "Passport", desc: "" },
        { value: "nationalId", label: "National ID", desc: "" },
        { value: "driversLicense", label: "Drivers License", desc: "" },
      ],
      documentUploadDescription: {
        passport: [
          "Uploaded passport image must be clearly visible & complete",
          "Passport must in valid period",
          "Provided passport data page must included your full name, date of birth & your photo",
        ],
        nationalId: [
          "Uploaded ID image must be clearly visible",
          "ID image must in valid period",
          "Provided ID must included your full name, date of birth & your photo",
        ],
        driversLicense: [
          "Uploaded driver license image must be clearly visible",
          "Driver license must in valid period",
          "Uploaded driver license image must be clearly visible",
        ],
      },
    },
    addressInfo: {
      title: "Address Information",
      desc: "Enter your address information help us to speed up the verification process.",
      addressLine1: "Address Line 1",
      addressLine2: "Address Line 2",
      city: "City",
      state: "State",
      zipCode: "Zip Code",
      country: "Country",
      permanentAddress: "Permanent Address",
      correspondenceAddress: "Correspondence Address",
    },
    addressInfoLowerCase: {
      correspondenceAddress: "correspondenceAddress",
      sameCorrespondenceAddress: "sameCorrespondenceAddress",
      country: "country",
      addressLine1: "addressLine1",
      addressLine2: "addressLine2",
      city: "city",
      state: "state",
      zipCode: "zipCode",
    },
    financialInfo: {
      title: "Financial Information",
      desc: " Fill in your financial information to help us speed up the verification process.",
      accountNo: "Account Number",
      ifsc: "IFSC",
      accountType: "Account Type",
      bankName: "Bank Name",
      accountHolderName: "Account Holder Name",
      accountDetails: "Account Details",
    },
    financialInfoLowerCase: {
      accountNo: "accountNo",
      ifsc: "ifsc",
      accountType: "accountType",
      bankName: "bankName",
      accountHolderName: "accountHolderName",
    },
  },
};
